---
# Launches an EC2 instance
- name: Launch an EC2 instance
  hosts: localhost
  gather_facts: yes

  tasks:
  - name: Load secrets
    ansible.builtin.include_vars:
      file: ./vars/secrets.yaml
          
  - name: Launch instance
    amazon.aws.ec2_instance:
      name: "{{ instance_name }}"
      instance_type: "{{ instance_type }}"
      region: ap-south-1
      key_name: "{{ key_name }}"
      image_id: "{{ ami }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ security_group_id }}"
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ storage }}"
          volume_type: gp3
      network_interfaces:
      - assign_public_ip: true
      wait: true
      count: 1
      user_data: "{{ lookup('ansible.builtin.template', './templates/user-data.j2') }}"
      tags:
        Name: "{{ instance_name }}"
    register: ec2_instance

  - name: Print public dns
    ansible.builtin.debug:
      var: ec2_instance.instances | map(attribute='public_dns_name') | list
...
